### ISSUE TITLE
TypeError: quote_from_bytes() expected bytes

### ISSUE THREAD

**Issue by anaschaudhary33** [adarsh-goel/FileStreamBot-pro#59]
```
2023-05-10 15:04:54,104 - pyrogram.dispatcher - ERROR - quote_from_bytes() expected bytes
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pyromod/listen/listen.py", line 237, in resolve_future
    await self.registered_handler(client, message, *args)
  File "/home/ubuntu/src/filestreambot-pro/Adarsh/bot/plugins/stream.py", line 99, in private_receive_handler
    stream_link = f"{Var.URL}watch/{str(log_msg.id)}/{quote_plus(get_name(log_msg))}?hash={get_hash(log_msg)}"
  File "/usr/lib/python3.10/urllib/parse.py", line 886, in quote_plus
    string = quote(string, safe + space, encoding, errors)
  File "/usr/lib/python3.10/urllib/parse.py", line 870, in quote
    return quote_from_bytes(string, safe)
  File "/usr/lib/python3.10/urllib/parse.py", line 895, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes
```

**Comment by adarsh-goel** [comment]
Still facing this issue??
